[package]
name = "rpackage"
version = "0.1.0"
authors = ["Johnny Norbeck <norbeck.johnny@gmail.com>"]
edition = "2018"

[[bin]]
name = "generate"
path = "src/generate.rs"

[[bin]]
name = "rpackage"
path = "src/main.rs"

[dependencies]
fuse = "0.3.1"
time = "0.1"
libc = "0.2.74"
byteorder = "1.3.4"
